modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="cpapi"
version="11"
displayName="Keepers of the Stones II: Colorful Powers API"
displayURL="https://esmods.com"
logoFile="logo.png"
credits="Created by Environment Studios"
authors="Environment Studios"
description="This mod is a tool for creating mods with magical artifacts and powers compatible with the Keepers of the Stones II mod"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.cpapi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.cpapi]]
    modId="power"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"



# Start of user code block dependencies configuration
# End of user code block dependencies configuration